import { DropPoint, MarketItem, ArtisanProfile, RewardVoucher } from './types';

export const IMPACT_CONSTANTS = {
  WATER_LITERS_PER_KG: 2700, // 1 kg tekstil = 2.700 liter air terhemat
  CO2_KG_PER_KG: 3.6,        // 1 kg tekstil = 3.6 kg CO2 terhindar
  POINTS_PER_KG: 100,        // 1 kg donasi = 100 ClothPoints
};

export const MOCK_DROP_POINTS: DropPoint[] = [
  {
    id: 'dp-1',
    name: 'ClothLoop Hub — Senopati Eco Lounge',
    category: 'Coffee Shop Partner',
    address: 'Jl. Senopati No. 42, Kebayoran Baru, Jakarta Selatan',
    city: 'Jakarta Selatan',
    latitude: -6.2345,
    longitude: 106.8123,
    operatingHours: 'Setiap Hari, 08:00 - 21:00 WIB',
    acceptedTypes: ['Pakaian Katun', 'Denim', 'Jaket / Outer', 'Linen', 'Tas Kain'],
    contactPhone: '+62 812-8899-1001',
    image: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=600&q=80',
    capacityPercentage: 45,
    totalCollectedKg: 1240,
  },
  {
    id: 'dp-2',
    name: 'Kopi Kenangan Berkelanjutan — Grand Indonesia',
    category: 'Mall Drop Box',
    address: 'Grand Indonesia West Mall Lt. 3, Jakarta Pusat',
    city: 'Jakarta Pusat',
    latitude: -6.1954,
    longitude: 106.8214,
    operatingHours: 'Setiap Hari, 10:00 - 22:00 WIB',
    acceptedTypes: ['Semua Jenis Baju', 'Bahan Rajut', 'Kain Perca', 'Sprei & Handuk Bekas'],
    contactPhone: '+62 813-7711-2002',
    image: 'https://images.unsplash.com/photo-1567449303078-57ad995bd301?auto=format&fit=crop&w=600&q=80',
    capacityPercentage: 78,
    totalCollectedKg: 2890,
  },
  {
    id: 'dp-3',
    name: 'ClothLoop Studio — Dago Heritage Creative Space',
    category: 'Retail Boutique',
    address: 'Jl. Ir. H. Juanda No. 128, Dago, Bandung',
    city: 'Bandung',
    latitude: -6.8856,
    longitude: 107.6143,
    operatingHours: 'Selasa - Minggu, 09:00 - 20:00 WIB',
    acceptedTypes: ['Denim Vintage', 'Batik Lawasan', 'Katun', 'Kain Katun Jepang'],
    contactPhone: '+62 821-4455-3003',
    image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=600&q=80',
    capacityPercentage: 30,
    totalCollectedKg: 1650,
  },
  {
    id: 'dp-4',
    name: 'Bank Sampah Induk Surabaya Timur',
    category: 'Bank Sampah Digital',
    address: 'Jl. Nginden Semolo No. 88, Sukolilo, Surabaya',
    city: 'Surabaya',
    latitude: -7.2965,
    longitude: 112.7661,
    operatingHours: 'Senin - Sabtu, 08:00 - 16:00 WIB',
    acceptedTypes: ['Semua Tekstil', 'Seragam Bekas', 'Potongan Konveksi', 'Pakaian Rusak Parah'],
    contactPhone: '+62 811-3322-4004',
    image: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&w=600&q=80',
    capacityPercentage: 85,
    totalCollectedKg: 4320,
  },
  {
    id: 'dp-5',
    name: 'Eco Bali Collective & ClothLoop Drop',
    category: 'Retail Boutique',
    address: 'Jl. Pantai Batu Bolong No. 65, Canggu, Bali',
    city: 'Bali',
    latitude: -8.6534,
    longitude: 115.1325,
    operatingHours: 'Setiap Hari, 09:00 - 21:00 WITA',
    acceptedTypes: ['Resort Wear', 'Linen', 'Swimwear', 'Pakaian Pantai', 'Katun Organik'],
    contactPhone: '+62 819-9988-5005',
    image: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?auto=format&fit=crop&w=600&q=80',
    capacityPercentage: 55,
    totalCollectedKg: 2110,
  },
  {
    id: 'dp-6',
    name: 'Batik Sirkular Space Prawirotaman',
    category: 'Coffee Shop Partner',
    address: 'Jl. Prawirotaman No. 24, Mergangsan, Yogyakarta',
    city: 'Yogyakarta',
    latitude: -7.8189,
    longitude: 110.3687,
    operatingHours: 'Setiap Hari, 09:00 - 22:00 WIB',
    acceptedTypes: ['Batik Perca', 'Tenun Bekas', 'Kain Etnik', 'Katun Ringan'],
    contactPhone: '+62 877-6655-6006',
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=600&q=80',
    capacityPercentage: 62,
    totalCollectedKg: 1890,
  }
];

export const MOCK_MARKET_ITEMS: MarketItem[] = [
  {
    id: 'mkt-1',
    title: 'Upcycled Denim Kimono Jacket — Sashiko Stitch',
    brand: 'ClothCraft Studio x Rere Artisan',
    sellerName: 'Rere Novitasari',
    sellerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
    sellerCity: 'Bandung',
    price: 345000,
    originalPrice: 750000,
    condition: 'UPCYCLED',
    category: 'Outerwear',
    size: 'L (Oversized)',
    measurements: {
      chestWidthCm: 58,
      lengthCm: 72,
      sleeveLengthCm: 56,
    },
    material: 'Upcycled Heavy Denim 14oz & Japanese Boro Stitching',
    story: 'Dibuat dari 2 pasang celana jeans vintage Levis tak terpakai, digabungkan dengan teknik sulam sashiko khas Jepang yang memakan waktu 18 jam pengerjaan.',
    images: [
      'https://images.unsplash.com/photo-1551537482-f2075a1d41f2?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1542272604-780c96856592?auto=format&fit=crop&w=600&q=80',
    ],
    waterSavedLiters: 10800,
    co2SavedKg: 14.4,
    isVerifiedQC: true,
    status: 'AVAILABLE',
    rating: 4.9,
    reviewCount: 24,
  },
  {
    id: 'mkt-2',
    title: 'Uniqlo U Premium Organic Linen Shirt (Mint Green)',
    brand: 'Uniqlo U Curated',
    sellerName: 'Dian Sastrowardoyo',
    sellerAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=150&q=80',
    sellerCity: 'Jakarta Selatan',
    price: 185000,
    originalPrice: 499000,
    condition: 'LIKE_NEW',
    category: 'Wanita',
    size: 'M',
    measurements: {
      chestWidthCm: 50,
      lengthCm: 68,
      sleeveLengthCm: 58,
    },
    material: '100% French Linen Organik',
    story: 'Baru dipakai 2 kali untuk photoshoot editorial. Kondisi serat sangat prima, kancing cadangan lengkap, sudah dicuci higienis dengan deterjen eco-friendly.',
    images: [
      'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=600&q=80',
    ],
    waterSavedLiters: 5400,
    co2SavedKg: 7.2,
    isVerifiedQC: true,
    status: 'AVAILABLE',
    rating: 5.0,
    reviewCount: 12,
  },
  {
    id: 'mkt-3',
    title: 'Patchwork Denim Tote Bag — Heavy Utility',
    brand: 'LimbahKarya Bali',
    sellerName: 'Wayan Gede',
    sellerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    sellerCity: 'Bali',
    price: 165000,
    originalPrice: 320000,
    condition: 'UPCYCLED',
    category: 'Upcycled Bags',
    size: 'All Size (40x35x10 cm)',
    measurements: {
      chestWidthCm: 40,
      lengthCm: 35,
    },
    material: 'Kombinasi Denim Perca & Furing Katun Daur Ulang',
    story: 'Ditenun dari sisa potongan celana jeans peselancar Canggu. Dilengkapi kompartemen laptop 14 inci dan kantong rahasia beresleting YKK kuningan.',
    images: [
      'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=600&q=80',
    ],
    waterSavedLiters: 8100,
    co2SavedKg: 10.8,
    isVerifiedQC: true,
    status: 'AVAILABLE',
    rating: 4.8,
    reviewCount: 38,
  },
  {
    id: 'mkt-4',
    title: 'Vintage 90s Ralph Lauren Chino Harrington Jacket',
    brand: 'Polo Ralph Lauren Vintage',
    sellerName: 'Retro Jakarta Vault',
    sellerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
    sellerCity: 'Jakarta Pusat',
    price: 480000,
    originalPrice: 1850000,
    condition: 'VINTAGE',
    category: 'Pria',
    size: 'XL',
    measurements: {
      chestWidthCm: 62,
      lengthCm: 70,
      sleeveLengthCm: 63,
    },
    material: '100% Heavy Twill Cotton, Tartan Lining',
    story: 'Original piece dari era 1995. Patina resleting original masih sangat mulus, warna beige khas vintage tanpa noda atau sobekan.',
    images: [
      'https://images.unsplash.com/photo-1548883354-7622d03aca27?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=600&q=80',
    ],
    waterSavedLiters: 13500,
    co2SavedKg: 18.0,
    isVerifiedQC: true,
    status: 'AVAILABLE',
    rating: 4.9,
    reviewCount: 19,
  },
  {
    id: 'mkt-5',
    title: 'Batik Cap Lawasan Reworked Short Sleeve Shirt',
    brand: 'Surakarta Heritage Rework',
    sellerName: 'Bagus Prakoso',
    sellerAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=150&q=80',
    sellerCity: 'Yogyakarta',
    price: 260000,
    originalPrice: 520000,
    condition: 'UPCYCLED',
    category: 'Pria',
    size: 'L',
    measurements: {
      chestWidthCm: 56,
      lengthCm: 73,
      sleeveLengthCm: 25,
    },
    material: 'Katun Primissima Batik Cap Pewarna Alam Indigo',
    story: 'Kain batik lawasan Solo berusia 30 tahun yang dipulihkan dan dijahit ulang menjadi kemeja kasual modern dengan siluet relaxed fit.',
    images: [
      'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1603252109303-2751441dd157?auto=format&fit=crop&w=600&q=80',
    ],
    waterSavedLiters: 6750,
    co2SavedKg: 9.0,
    isVerifiedQC: true,
    status: 'AVAILABLE',
    rating: 5.0,
    reviewCount: 41,
  },
  {
    id: 'mkt-6',
    title: 'Zara Floral Wrap Midi Dress (Eco Collection)',
    brand: 'Zara Sustainable',
    sellerName: 'Amira Larasati',
    sellerAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80',
    sellerCity: 'Surabaya',
    price: 195000,
    originalPrice: 699000,
    condition: 'GENTLY_USED',
    category: 'Wanita',
    size: 'S',
    measurements: {
      chestWidthCm: 46,
      lengthCm: 110,
    },
    material: '100% EcoVero Viscose',
    story: 'Dipakai 3 kali untuk acara santai. Bahan sangat adem dan flowy, motif bunga vintage cerah.',
    images: [
      'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=600&q=80',
    ],
    waterSavedLiters: 4800,
    co2SavedKg: 6.4,
    isVerifiedQC: true,
    status: 'AVAILABLE',
    rating: 4.7,
    reviewCount: 16,
  }
];

export const MOCK_ARTISANS: ArtisanProfile[] = [
  {
    id: 'art-1',
    name: 'Rere Novitasari',
    workshopName: 'BoroBoro Studio Bandung',
    specialty: ['Denim Rework', 'Sashiko Embroidery', 'Boro Patchwork'],
    city: 'Bandung',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    coverImage: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?auto=format&fit=crop&w=800&q=80',
    rating: 4.98,
    completedOrders: 184,
    yearsOfExperience: 6,
    bio: 'Pencinta tekstil daur ulang dengan spesialisasi sulam tangan Sashiko tradisional Jepang dan rekonstruksi denim berat. Berkomitmen memberi nafas kedua bagi jaket & celana robek.',
    startingPrice: 85000,
    isAvailable: true,
    portfolio: [
      {
        id: 'pf-1',
        title: 'Jeans Robek Parah ➔ Sashiko Repair Kimono',
        beforeImage: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=500&q=80',
        afterImage: 'https://images.unsplash.com/photo-1551537482-f2075a1d41f2?auto=format&fit=crop&w=500&q=80',
        description: 'Dua celana jeans usang dirombak total menjadi satu jaket kimono beraksen sulaman putih kontras.',
        price: 280000,
      },
      {
        id: 'pf-2',
        title: 'Kemeja Katun Sobek ➔ Patchwork Bucket Hat',
        beforeImage: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=500&q=80',
        afterImage: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=500&q=80',
        description: 'Potongan kemeja kotak-kotak disatukan menjadi bucket hat reversibel dua sisi.',
        price: 110000,
      }
    ]
  },
  {
    id: 'art-2',
    name: 'Wayan Gede & Team',
    workshopName: 'Canggu Craft Collective',
    specialty: ['Upcycled Bags', 'Sailcloth & Canvas', 'Hardware Replacement'],
    city: 'Bali',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    coverImage: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80',
    rating: 4.92,
    completedOrders: 310,
    yearsOfExperience: 8,
    bio: 'Studio kerajinan Bali yang mengubah limbah tekstil celana jeans, kain layar kapal, dan tenda bekas menjadi tas utility dan pouch tahan lama.',
    startingPrice: 120000,
    isAvailable: true,
    portfolio: [
      {
        id: 'pf-3',
        title: 'Celana Jeans ➔ Commuter Messenger Bag',
        beforeImage: 'https://images.unsplash.com/photo-1542272604-780c96856592?auto=format&fit=crop&w=500&q=80',
        afterImage: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=500&q=80',
        description: 'Kantong belakang celana jeans dipertahankan sebagai saku luar botol minum yang fungsional.',
        price: 240000,
      }
    ]
  },
  {
    id: 'art-3',
    name: 'Ibu Siti Khadijah',
    workshopName: 'Batik Restorasi Prawirotaman',
    specialty: ['Batik Heritage Repair', 'Natural Indigo Dye', 'Kebaya Modern Alteration'],
    city: 'Yogyakarta',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80',
    coverImage: 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?auto=format&fit=crop&w=800&q=80',
    rating: 5.0,
    completedOrders: 92,
    yearsOfExperience: 22,
    bio: 'Maestro penjahit tradisional Jogja spesialis reparasi kain batik warisan turun-temurun, permak kebaya nenek menjadi gaun modern, dan pewarnaan ulang alami.',
    startingPrice: 75000,
    isAvailable: true,
    portfolio: [
      {
        id: 'pf-4',
        title: 'Batik Tulis Rapuh ➔ Outerwear Sutra Modern',
        beforeImage: 'https://images.unsplash.com/photo-1603252109303-2751441dd157?auto=format&fit=crop&w=500&q=80',
        afterImage: 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?auto=format&fit=crop&w=500&q=80',
        description: 'Penguatan lapisan interfacing pada kain batik rapuh tahun 1980 sehingga kokoh dipakai harian.',
        price: 320000,
      }
    ]
  }
];

export const MOCK_REWARD_VOUCHERS: RewardVoucher[] = [
  {
    id: 'vch-1',
    title: 'Diskon Rp 50.000 Belanja ClothMarket',
    partnerBrand: 'ClothMarket Official',
    logo: '🛍️',
    category: 'Discount',
    pointsCost: 350,
    description: 'Potongan langsung Rp 50.000 untuk belanja pakaian preloved terkurasi di ClothMarket dengan minimal transaksi Rp 150.000.',
    discountValue: 'Rp 50.000 OFF',
    validUntil: '31 Des 2026',
    terms: ['Minimal belanja Rp 150.000', 'Berlaku untuk semua kategori preloved', 'Dapat digabung dengan gratis ongkir']
  },
  {
    id: 'vch-2',
    title: 'Free Oat Milk Latte di Partner Coffee Shop',
    partnerBrand: 'Kopi Kenangan & Tanamera',
    logo: '☕',
    category: 'Eco Coffee',
    pointsCost: 250,
    description: 'Nikmati 1 cup kopi plant-based gratis saat kamu mengantarkan pakaian donasi ke drop-point kafe rekanan ClothLoop.',
    discountValue: '1 FREE CUP',
    validUntil: '15 Nov 2026',
    terms: ['Tunjukkan voucher saat drop pakaian', 'Pilihan kopi susu plant-based atau Americano', '1 voucher per kunjungan']
  },
  {
    id: 'vch-3',
    title: 'Voucher Jasa Upcycling ClothCraft Rp 75.000',
    partnerBrand: 'BoroBoro & ClothCraft',
    logo: '🧵',
    category: 'Upcycle Workshop',
    pointsCost: 500,
    description: 'Potongan biaya jasa rework pakaian lama menjadi fashion item baru bersama artisan bersertifikat kami.',
    discountValue: 'Rp 75.000 OFF',
    validUntil: '31 Des 2026',
    terms: ['Berlaku untuk minimum pesanan kustom Rp 150.000', 'Dapat digunakan untuk semua mitra artisan']
  },
  {
    id: 'vch-4',
    title: 'Adopsi 1 Bibit Pohon Mangrove Pesisir Jawa',
    partnerBrand: 'LindungiHutan x ClothLoop',
    logo: '🌱',
    category: 'Tree Planting',
    pointsCost: 400,
    description: 'Konversikan poinmu untuk menanam 1 bibit mangrove di pesisir Pantura. Kamu akan menerima sertifikat digital koordinat pohonmu.',
    discountValue: '1 POHON',
    validUntil: 'Sepanjang Tahun',
    terms: ['Sertifikat digital dikirim ke email dalam 24 jam', 'Laporan monitoring pohon setiap 3 bulan']
  }
];

export const NATIONAL_IMPACT_METRICS = {
  totalDivertedKg: 148920, // kg pakaian
  totalWaterSavedLiters: 402084000, // Liter air
  totalCo2AvoidedKg: 536112, // kg CO2
  activeDonors: 18450,
  activeArtisans: 142,
  partnerDropPoints: 68,
};
